// CONTACTS
export const GET_CONTACTS = 'GET_CONTACTS'
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_CONTACTS = 'CONTACT_ERROR';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CONTACT_ERROR = 'CONTACT_ERROR'

//ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//INFOSHOTS
export const ADD_INFOBOX = 'ADD_INFOBOX';
export const DELETE_INFOBOX = 'DELETE_INFOBOX';
export const SET_CURRENT_INFOBOX = 'SET_CURRENT_INFOBOX';
export const CLEAR_CURRENT_INFOBOX = 'CLEAR_CURRENT_INFOBOX';
export const UPDATE_INFOBOX = 'UPDATE_INFOBOX';
export const FILTER_INFOBOXES = 'FILTER_INFOBOXES';
export const CLEAR_FILTER_INFOBOX = 'CLEAR_FILTER_INFOBOX';
export const INFOBOX_ERROR = 'INFOBOX_ERROR'

//LOGIN
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
