// Contacts
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//Infoshots
export const ADD_INFOBOX = 'ADD_INFOBOX';
export const DELETE_INFOBOX = 'DELETE_INFOBOX';
export const SET_CURRENT_INFOBOX = 'SET_CURRENT_INFOBOX';
export const CLEAR_CURRENT_INFOBOX = 'CLEAR_CURRENT_INFOBOX';
export const UPDATE_INFOBOX = 'UPDATE_INFOBOX';
export const FILTER_INFOBOXES = 'FILTER_INFOBOXES';
export const CLEAR_FILTER_INFOBOX = 'CLEAR_FILTER_INFOBOX';
// export const SET_ALERT = 'SET_ALERT';
// export const REMOVE_ALERT = 'REMOVE_ALERT';
